cd ..
jac-run scripts/graph/learn_graph_tasks.py \
    --task grail-nell_v3 \
    --epochs 100 \
    --test-interval 1 \
    --save-interval 5 \
    --early-stop 1e-8 \
    --use-gpu \
    --test-number-begin 100 \
    --test-number-step 0 \
    --test-number-end 100 \
    --model nlm \
    --nlm-norm tanh \
    --nlm-depth 6 \
    --nlm-attributes 100 \
    --seed 666 \
    --batch-size 128 \
    --sparsity-loss-ratio 0 \
    --subgraph single \
    --single-link-pred-bridge path \
    --subgraph-size 15 \
    --link-pred-k 3 \
    --resample 100000 \
    --test-subgraph-size 15 \
    --test-batch-size 128 \
    --epoch-size 500 \
    --test-epoch-size 50 \
    --lr 0.001 \
    --aug-node-feature-dim 0 \
    --num-rels 142 \
    --task-is-directed \
    --nlm-reducer mean \
    --dump-dir log/nlm_single/nell_v3